### ISSUE TITLE
/randomSong not working

### ISSUE THREAD

**Issue by gloriousnoise** [samuri51/chillybot#55]
Console says songs changed, but they are not reordered.

**Comment by samuri51** [comment]
how are you using this command? when the bot is playing or when it is on the floor?

**Comment by samuri51** [comment]
without testing it i suspect the bot needs to not be playing it's song to do that command since it tries to swap out the first song in it's Q with a different one. can you try again when it's not playing?

**Comment by gloriousnoise** [comment]
I've tried it both ways.

**Comment by samuri51** [comment]
fixed it. you were right, it wasn't calculating correctly, sorry haha. see if it works now

**Comment by gloriousnoise** [comment]
Worked!

**Comment by samuri51** [comment]
sweet
